### ISSUE TITLE
Feature - Modifier to skip using UI

### ISSUE THREAD

**Issue by BaalEvan** [Dakraid/RW_DSGUI#10]
Hi! I found deconstructing barrel with food is a bit problematic because i can only select foods and not a barrel, perhaps RClick with Ctrl or something to open default UI or adding standard options to new UI could be useful ;)

**Comment by BaalEvan** [comment]
Or maybe you could add storageBuilding to UI list at top or bottom then we should be able to select Deconstruct or Move from UI ;)

**Comment by lilwhitemouse** [comment]
If you right-click while you have an item selected, it will jump to the storage unit.

Does that do what you wanted?

**Comment by BaalEvan** [comment]
Not really because Pawn isn't a item right? And I want to prioritize deconstruct for example so i must have pawn selected

**Comment by Dakraid** [comment]
I'm aware of this issue and plan to address this for 1.3

Due to changes in the structure I will close this issue for now, any discussion can be continued here: Issue #17
