### ISSUE TITLE
[BUG] Broken list creation causing issues with scrolling

### ISSUE THREAD

**Issue by Dakraid** [Dakraid/RW_DSGUI#20]
**Describe the bug**
From a comment on the mod page:

> Right now the "scrolling" feature is broken for me, it used to be not, but for some reason it stopped working.
> Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
> Verse.Log:Error(String, Boolean)
> Verse.Widgets:EnsureMousePositionStackEmpty()
> Verse.Root:Verse.Root.Update_Patch1(Root)
> Verse.Root_Play:Verse.Root_Play.Update_Patch1(Root_Play)
> I have a lot of weird red errors in my modlist that don't do anything but this one only makes the storage show the "first" object listed.
> Brand new save so it's not something from removing mods or updating.

**To Reproduce**
To be determined.

**Expected behavior**
Render the scroll view as usual.

**Comment by Mx772** [comment]
Not sure if entirely separate issue here, but I am getting a loop of this error with the addition of the one most recently mentioned in the steam discussion:
https://steamcommunity.com/workshop/filedetails/discussion/2169841018/4078523564597472114/

Pastebin:
https://pastebin.com/ySYTcH4X

Error loop:
```
Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.Widgets:EnsureMousePositionStackEmpty()
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Update()
 
Exception filling window for DSGUI.DSGUI_ListModal: System.NullReferenceException: Object reference not set to an instance of an object
  at DSGUI.DSGUI_ListItem.DoDraw (UnityEngine.Rect inRect, System.Single y, System.Boolean altBG) [0x000c9] in <e8fe17b4d1cb45d0a22de279c73aec9d>:0 
  at DSGUI.DSGUI_ListModal.DoWindowContents (UnityEngine.Rect inRect) [0x00353] in <e8fe17b4d1cb45d0a22de279c73aec9d>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x00165] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

The strange part is it worked before I saved/reloaded. 

Now on save, It doesn't seem to load for me.
