### ISSUE TITLE
Untested Search Bar/Function

### ISSUE THREAD

**Issue by humdedum1** [Dakraid/RW_DSGUI#4]
Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
Verse.Log:Error(String, Boolean)
Verse.Widgets:EnsureMousePositionStackEmpty()
Verse.Root:DMD<DMD<Update_Patch1>?-779002112::Update_Patch1>(Root)
Verse.Root_Play:DMD<DMD<Update_Patch1>?-248443392::Update_Patch1>(Root_Play)

Makes Contents UI blank; as well as any other UI window like the Debug Log. 

https://i.imgur.com/3pmWio8.jpg
Picture of said blank windows.

**Comment by Dakraid** [comment]
Addressed in commit [bfe09c1](https://github.com/Dakraid/RW_DSGUI/commit/bfe09c19f5a07fb6bf263d6bd44e6db8820a72a7)
